APIGOV-23841 - add trace logging for flush out harvester connect issue
Axway/agent-sdk pull request #567
Opened 2022-10-12 17:50 UTC by sbolosan

@jcollins-axway @tsjohns9 - I feel like some of the trace logging is lame, like doesn't really do anything except leave bread crumbs to the real error.  And maybe that's what we want.  Let me know if you need me to add more/take away ...  thanks.

2022-10-12 17:57 UTC, jcollins-axway requested changes
This does not need to be merged into the SDK, until we discover the actual issue. We can give a feature build for just the logging while we investigate.

2022-10-12 17:58 UTC, jcollins-axway commented
I am fine with all the logging, verbose or not, as it is trace level and meant only for developers

2022-10-12 18:01 UTC, sbolosan commented
@jcollins-axway right.. i will close this after we get what we need.  I already pinged Ethan and that's where I was going... was going to ask if he is ok taking a build from me

2022-10-12 18:38 UTC, tsjohns9 commented on pkg/agent/poller/client.go
> +		WithComponent("pollExecutor").
should be PollClient

2022-10-12 18:39 UTC, tsjohns9 submitted a review, later dismissed

2022-10-12 18:39 UTC, sbolosan commented on pkg/agent/poller/client.go
> +		WithComponent("pollExecutor").
oops, you're right... copy paste

2022-10-13 16:19 UTC, tsjohns9 submitted a review, later dismissed

2022-10-13 21:30 UTC, sbolosan commented
Reverted most of the traces.  Now on startup, using ticker and ticker timeout to check hc status.
ticker - check every 5 seconds
tickerTImeout - exhaust after 5 minutes...

fail if 5 mins exhaust

2022-10-13 22:18 UTC, jcollins-axway commented
I think some of the logging that was added may be beneficial. It may be verbose but in some cases nice to see when the code gets in and out of functions.

2022-10-13 22:18 UTC, jcollins-axway submitted a review, later dismissed

2022-10-13 22:23 UTC, sbolosan commented
@jcollins-axway , i have the trace version sent out to Ethan/laura to test tomorrow.  I will reintroduce the ones that make sense 🤙🏾

2022-10-14 15:23 UTC, jcollins-axway approved these changes

2022-10-14 15:25 UTC, vivekschauhan approved these changes

2022-10-14 15:29 UTC, merged