APIGOV-26893 - new usage report generation logic
Axway/agent-sdk pull request #716
Opened 2024-01-09 10:36 UTC by dgghinea

2024-01-09 19:51 UTC, jcollins-axway commented
This seems to update the report as it is going into the cache, which is not the desired place for this. We want the aggregation to occur as the report is being sent to the platform and to not affect the offline reporting that this change looks like it will.

2024-01-09 19:51 UTC, jcollins-axway requested changes
see above comment

2024-01-16 14:22 UTC, jcollins-axway approved these changes

2024-01-19 15:58 UTC, vivekschauhan approved these changes

2024-01-22 07:30 UTC, merged